### ISSUE TITLE
NotificationResponse{error=null, httpStatusCode=-1, responseBody='null', cause=java.util.concurrent.TimeoutException}

### ISSUE THREAD

**Issue by hgz07** [CleverTap/apns-http2#2]
import java.io.*;
import com.clevertap.jetty.apns.http2.*;
public class MyMain {
    public static void main(String[] args) {
        try {
            FileInputStream cert = new FileInputStream("~/Documents/apns.p12");
            final ApnsClient client = new ApnsClientBuilder()
                    .withProductionGateway()
                    .inSynchronousMode()
                    .withCertificate(cert)
                    .withPassword("my password")
                    .build();
            client.start();
            Notification n = new Notification.Builder("my token")
                    .alertBody("Hello").build();
            NotificationResponse result = client.push(n);
            System.out.println(result);
        }catch (Exception e){
            return;
        }
    }
}

**Comment by judepereira** [comment]
Hey @hgz07, could you update the client? I've just committed a whole bunch of certificate related checks, which might aid you in this case.

Also, ensure that you have the ALPN boot library in your boot classpath, and that you're running it on Java 8 with the appropriate ALPN JAR version.

**Comment by hgz07** [comment]
I 've update the client source. But error still occurred:
[main] INFO org.eclipse.jetty.util.log - Logging initialized @329ms
[main] INFO org.eclipse.jetty.util.ssl.SslContextFactory - x509=X509@5702b3b1(espace2_apns,h=[],w=[]) for SslContextFactory@69ea3742(null,null)
NotificationResponse{error=null, httpStatusCode=-1, responseBody='null', cause=java.util.concurrent.TimeoutException}

=======================
and my project have the ALPN lib:
alpn-api-1.1.2.v20150522.jar
jetty-alpn-client-9.3.7.v20160115.jar
jetty-io-9.3.7.v20160115.jar
jetty-util-9.3.7.v20160115.jar
======================
@judepereira,  Help me please.      THKS

**Comment by judepereira** [comment]
Can you try using the okHttp client?

**Comment by joe1100** [comment]
-Xbootclasspath/p:C:/Users/Administrator/.m2/repository/org/mortbay/jetty/alpn/alpn-boot/8.1.6.v20151105/alpn-boot-8.1.6.v20151105.jar
